In [1]:
import os

os.environ["KERAS_BACKEND"] = "tensorflow"

In [2]:
import tensorflow as tf
import pandas as pd
import keras as kr
import pathlib as pl
import numpy as np

In [3]:
inference_model_path = pl.Path("../models/inference_model.keras")
training_model_path = pl.Path("../models/training_model.keras")
titanic_data_test_path = pl.Path("../data/raw/train.csv")

inference_model_path.resolve()
training_model_path.resolve()
titanic_data_test_path.resolve()

WindowsPath('C:/Users/blanc/Documents/GitHub/titanic-ml-tfpj/data/raw/train.csv')

In [4]:
titanic_data_test = pd.read_csv(filepath_or_buffer=titanic_data_test_path)
titanic_data_test.loc[titanic_data_test["Embarked"].isna(), "Embarked"] = "D"
titanic_data_test = titanic_data_test.loc[
    :,
    [
        "Pclass",
        "Sex",
        "Age",
        "SibSp",
        "Parch",
        "Fare",
        "Embarked",
    ],
]
print("Se deben predecir un total de {} casos".format(len(titanic_data_test)))

Se deben predecir un total de 891 casos


In [5]:
# input_dict = {name: tf.convert_to_tensor(value) for name, value in sample.items()}
titanic_dataset = tf.data.Dataset.from_tensors(tensors=dict(titanic_data_test))

print(
    "Se deben predecir un total de {} casos".format(
        len(titanic_dataset),
    ),
)

Se deben predecir un total de 1 casos


In [6]:
list(titanic_dataset)

[{'Pclass': <tf.Tensor: shape=(891,), dtype=int64, numpy=
  array([3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2,
         3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 3, 2, 1, 1, 3, 3, 3, 3, 3, 2, 3, 2,
         3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 1, 1, 2, 3, 2, 3, 3, 1, 1, 3, 1, 3,
         2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 2, 3, 3, 3,
         1, 3, 3, 3, 1, 3, 3, 3, 1, 1, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3,
         1, 3, 3, 3, 3, 3, 3, 2, 1, 3, 2, 3, 2, 2, 1, 3, 3, 3, 3, 3, 3, 3,
         3, 2, 2, 2, 1, 1, 3, 1, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3,
         3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 1, 3,
         3, 1, 2, 3, 3, 2, 3, 2, 3, 1, 3, 1, 3, 3, 2, 2, 3, 2, 1, 1, 3, 3,
         3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 2, 1, 2,
         3, 2, 3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 2, 3, 2, 3, 2, 2, 2, 2, 3, 3,
         2, 3, 3, 1, 3, 2, 1, 2, 3, 3, 1, 3, 3, 3, 1, 1, 1, 2, 3, 3, 1, 1,
         3, 2, 3, 3, 1, 1, 1, 3, 2, 1, 3, 

In [7]:
inference_model = kr.models.load_model(filepath=inference_model_path)
training_model = kr.models.load_model(filepath=training_model_path)

In [8]:
sample = titanic_data_test.sample(n=1)
input_dict = {name: tf.convert_to_tensor(value) for name, value in sample.items()}
input_dict

{'Pclass': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([3], dtype=int64)>,
 'Sex': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'female'], dtype=object)>,
 'Age': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([26.])>,
 'SibSp': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0], dtype=int64)>,
 'Parch': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0], dtype=int64)>,
 'Fare': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([7.925])>,
 'Embarked': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'S'], dtype=object)>}

In [9]:
prediction = inference_model.predict(input_dict)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step


array([[0.42210525]], dtype=float32)

In [10]:
predictions = inference_model.predict(x=titanic_dataset)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step


array([[0.06226229],
       [0.98524046],
       [0.42210528],
       [0.9874074 ],
       [0.0602196 ],
       [0.03987905],
       [0.2555308 ],
       [0.04276018],
       [0.8191519 ],
       [0.9810582 ],
       [0.54381096],
       [0.9705486 ],
       [0.06773431],
       [0.03616178],
       [0.36961085],
       [0.8797046 ],
       [0.02858267],
       [0.0935005 ],
       [0.19146827],
       [0.6111609 ],
       [0.06280035],
       [0.05715452],
       [0.83902884],
       [0.47905535],
       [0.12111206],
       [0.06434729],
       [0.08680065],
       [0.07200352],
       [0.83865976],
       [0.04605198],
       [0.19396788],
       [0.99547225],
       [0.83834136],
       [0.05598091],
       [0.09861276],
       [0.28420934],
       [0.08680216],
       [0.06773431],
       [0.19417575],
       [0.4704881 ],
       [0.12461109],
       [0.8568641 ],
       [0.08704498],
       [0.9513536 ],
       [0.41686213],
       [0.0461596 ],
       [0.07946019],
       [0.838

In [11]:
len(predictions)

891

In [12]:
predictions.shape

(891, 1)

In [13]:
passanger_id = np.arange(1, len(predictions) + 1)
passanger_id

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [14]:
predictions_reshape = np.reshape(a=predictions, newshape=len(predictions))
predictions_reshape

array([0.06226229, 0.98524046, 0.42210528, 0.9874074 , 0.0602196 ,
       0.03987905, 0.2555308 , 0.04276018, 0.8191519 , 0.9810582 ,
       0.54381096, 0.9705486 , 0.06773431, 0.03616178, 0.36961085,
       0.8797046 , 0.02858267, 0.0935005 , 0.19146827, 0.6111609 ,
       0.06280035, 0.05715452, 0.83902884, 0.47905535, 0.12111206,
       0.06434729, 0.08680065, 0.07200352, 0.83865976, 0.04605198,
       0.19396788, 0.99547225, 0.83834136, 0.05598091, 0.09861276,
       0.28420934, 0.08680216, 0.06773431, 0.19417575, 0.4704881 ,
       0.12461109, 0.8568641 , 0.08704498, 0.9513536 , 0.41686213,
       0.0461596 , 0.07946019, 0.83834136, 0.19827637, 0.3949044 ,
       0.01839225, 0.06747911, 0.986849  , 0.95283043, 0.19679676,
       0.25030407, 0.9170681 , 0.20809646, 0.9212719 , 0.00747689,
       0.1402946 , 0.9959955 , 0.35224858, 0.07966739, 0.12535122,
       0.67305267, 0.96213585, 0.06784517, 0.09991685, 0.10289884,
       0.15130086, 0.03506642, 0.11313321, 0.22417943, 0.22775

In [15]:
predictions_round = np.where(predictions_reshape > 0.5, 1, 0)
predictions_round

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,

In [16]:
predictions_by_pid = pd.DataFrame(
    data={"PassengerId": passanger_id, "Survived": predictions_round}
)

predictions_by_pid

PassengerId  Survived
0              1         0
1              2         1
2              3         0
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]