In [1]:
import os

os.environ["KERAS_BACKEND"] = "tensorflow"

In [2]:
import tensorflow as tf
import pandas as pd
import keras as kr
import pathlib as pl
import numpy as np

In [3]:
inference_model_path = pl.Path("../models/inference_model.keras")
training_model_path = pl.Path("../models/training_model.keras")
titanic_data_test_path = pl.Path("../data/raw/train.csv")

inference_model_path.resolve()
training_model_path.resolve()
titanic_data_test_path.resolve()

WindowsPath('C:/Users/blanc/Documents/GitHub/titanic-ml-tfp/data/raw/train.csv')

In [4]:
titanic_data_test = pd.read_csv(filepath_or_buffer=titanic_data_test_path)
titanic_data_test.loc[titanic_data_test["Embarked"].isna(), "Embarked"] = "D"
titanic_data_test = titanic_data_test.loc[
    :,
    [
        "Pclass",
        "Sex",
        "Age",
        "SibSp",
        "Parch",
        "Fare",
        "Embarked",
    ],
]
print("Se deben predecir un total de {} casos".format(len(titanic_data_test)))

Se deben predecir un total de 891 casos


In [5]:
# input_dict = {name: tf.convert_to_tensor(value) for name, value in sample.items()}
titanic_dataset = tf.data.Dataset.from_tensors(tensors=dict(titanic_data_test))

print(
    "Se deben predecir un total de {} casos".format(
        len(titanic_dataset),
    ),
)

Se deben predecir un total de 1 casos


In [6]:
list(titanic_dataset)

[{'Pclass': <tf.Tensor: shape=(891,), dtype=int64, numpy=
  array([3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2,
         3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 3, 2, 1, 1, 3, 3, 3, 3, 3, 2, 3, 2,
         3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 1, 1, 2, 3, 2, 3, 3, 1, 1, 3, 1, 3,
         2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 2, 3, 3, 3,
         1, 3, 3, 3, 1, 3, 3, 3, 1, 1, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3,
         1, 3, 3, 3, 3, 3, 3, 2, 1, 3, 2, 3, 2, 2, 1, 3, 3, 3, 3, 3, 3, 3,
         3, 2, 2, 2, 1, 1, 3, 1, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3,
         3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 1, 3,
         3, 1, 2, 3, 3, 2, 3, 2, 3, 1, 3, 1, 3, 3, 2, 2, 3, 2, 1, 1, 3, 3,
         3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 2, 1, 2,
         3, 2, 3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 2, 3, 2, 3, 2, 2, 2, 2, 3, 3,
         2, 3, 3, 1, 3, 2, 1, 2, 3, 3, 1, 3, 3, 3, 1, 1, 1, 2, 3, 3, 1, 1,
         3, 2, 3, 3, 1, 1, 1, 3, 2, 1, 3, 

In [7]:
inference_model = kr.models.load_model(filepath=inference_model_path)
training_model = kr.models.load_model(filepath=training_model_path)

In [8]:
sample = titanic_data_test.sample(n=1)
input_dict = {name: tf.convert_to_tensor(value) for name, value in sample.items()}
input_dict

{'Pclass': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([2], dtype=int64)>,
 'Sex': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'female'], dtype=object)>,
 'Age': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([4.])>,
 'SibSp': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1], dtype=int64)>,
 'Parch': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1], dtype=int64)>,
 'Fare': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([23.])>,
 'Embarked': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'S'], dtype=object)>}

In [9]:
prediction = inference_model.predict(input_dict)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step


array([[0.993184]], dtype=float32)

In [10]:
predictions = inference_model.predict(x=titanic_dataset)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[0.05701197],
       [0.9815234 ],
       [0.75580287],
       [0.97204787],
       [0.07413565],
       [0.0681882 ],
       [0.23828526],
       [0.11711147],
       [0.89393795],
       [0.9784754 ],
       [0.6905775 ],
       [0.97732615],
       [0.07377546],
       [0.01028379],
       [0.36300373],
       [0.8753906 ],
       [0.04339106],
       [0.19981164],
       [0.5252084 ],
       [0.7525909 ],
       [0.05060114],
       [0.05523799],
       [0.9113914 ],
       [0.42637715],
       [0.19293302],
       [0.12480571],
       [0.10533528],
       [0.01470271],
       [0.9115223 ],
       [0.12220655],
       [0.3062078 ],
       [0.9901994 ],
       [0.9116349 ],
       [0.0559787 ],
       [0.7863868 ],
       [0.32528707],
       [0.10533631],
       [0.07377546],
       [0.28653058],
       [0.5844018 ],
       [0.3178981 ],
       [0.75665677],
       [0.10549946],
       [0.9875815 ],
       [0.4604545 ],
       [0.12221698],
       [0.07707734],
       [0.911

In [11]:
len(predictions)

891

In [12]:
predictions.shape

(891, 1)

In [13]:
passanger_id = np.arange(1, len(predictions) + 1)
passanger_id

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [14]:
predictions_reshape = np.reshape(a=predictions, newshape=len(predictions))
predictions_reshape

array([0.05701197, 0.9815234 , 0.75580287, 0.97204787, 0.07413565,
       0.0681882 , 0.23828526, 0.11711147, 0.89393795, 0.9784754 ,
       0.6905775 , 0.97732615, 0.07377546, 0.01028379, 0.36300373,
       0.8753906 , 0.04339106, 0.19981164, 0.5252084 , 0.7525909 ,
       0.05060114, 0.05523799, 0.9113914 , 0.42637715, 0.19293302,
       0.12480571, 0.10533528, 0.01470271, 0.9115223 , 0.12220655,
       0.3062078 , 0.9901994 , 0.9116349 , 0.0559787 , 0.7863868 ,
       0.32528707, 0.10533631, 0.07377546, 0.28653058, 0.5844018 ,
       0.3178981 , 0.75665677, 0.10549946, 0.9875815 , 0.4604545 ,
       0.12221698, 0.07707734, 0.9116349 , 0.23229979, 0.3889504 ,
       0.05867792, 0.07367533, 0.98335534, 0.9869133 , 0.1126862 ,
       0.30955073, 0.96371263, 0.2147619 , 0.9907943 , 0.02843964,
       0.2841488 , 0.99332917, 0.29401845, 0.1011811 , 0.13922036,
       0.5619972 , 0.97457784, 0.07381885, 0.15419503, 0.03260846,
       0.09135986, 0.15900606, 0.04058167, 0.11927892, 0.42690

In [25]:
predictions_round = np.where(predictions_reshape > 0.5, 1, 0)
predictions_round

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,

In [26]:
predictions_by_pid = pd.DataFrame(
    data={"PassengerId": passanger_id, "Survived": predictions_round}
)

predictions_by_pid

PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]