In [1]:
import os

os.environ["KERAS_BACKEND"] = "tensorflow"

In [2]:
import tensorflow as tf
import pandas as pd
import keras as kr
import pathlib as pl
import numpy as np

In [3]:
inference_model_path = pl.Path("../models/inference_model.keras")
training_model_path = pl.Path("../models/training_model.keras")
titanic_data_test_path = pl.Path("../data/raw/test.csv")

inference_model_path.resolve()
training_model_path.resolve()
titanic_data_test_path.resolve()

WindowsPath('C:/Users/blanc/Documents/GitHub/titanic-ml-tfpj/data/raw/test.csv')

In [4]:
titanic_data_test = pd.read_csv(filepath_or_buffer=titanic_data_test_path)
titanic_data_test.loc[titanic_data_test["Embarked"].isna(), "Embarked"] = "D"
titanic_data_test = titanic_data_test.loc[
    :,
    [
        "Pclass",
        "Sex",
        "Age",
        "SibSp",
        "Parch",
        "Fare",
        "Embarked",
    ],
]
print("Se deben predecir un total de {} casos".format(len(titanic_data_test)))

Se deben predecir un total de 418 casos


In [37]:
# input_dict = {name: tf.convert_to_tensor(value) for name, value in sample.items()}
titanic_dataset = tf.data.Dataset.from_tensors(tensors=dict(titanic_data_test))

print(
    "Se deben predecir un total de {} casos".format(
        len(titanic_dataset),
    ),
)

Se deben predecir un total de 1 casos


In [38]:
list(titanic_dataset)

[{'Pclass': <tf.Tensor: shape=(418,), dtype=int64, numpy=
  array([3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 1, 1, 2, 1, 2, 2, 3, 3, 3, 1, 3,
         1, 1, 1, 3, 1, 3, 1, 3, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 2,
         1, 3, 1, 3, 1, 3, 1, 2, 2, 1, 2, 3, 3, 3, 3, 1, 3, 2, 3, 3, 1, 2,
         3, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 2, 3, 3, 1, 1, 3, 2, 3, 3, 3,
         3, 2, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 1, 2, 3, 3, 3, 3, 3, 3, 3, 2,
         2, 3, 1, 3, 1, 3, 3, 3, 1, 2, 2, 3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 1,
         3, 3, 3, 3, 3, 2, 3, 3, 3, 1, 1, 2, 1, 3, 1, 3, 1, 2, 1, 3, 3, 3,
         3, 3, 1, 3, 1, 3, 3, 3, 2, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 2,
         2, 1, 2, 1, 2, 1, 1, 3, 1, 2, 2, 3, 3, 2, 2, 1, 3, 2, 2, 3, 1, 3,
         2, 3, 3, 3, 1, 2, 2, 1, 3, 2, 1, 3, 3, 3, 2, 2, 3, 1, 3, 1, 1, 3,
         2, 3, 2, 3, 1, 3, 3, 3, 3, 2, 2, 1, 3, 3, 1, 3, 1, 3, 2, 1, 1, 2,
         1, 3, 3, 1, 2, 2, 2, 3, 2, 3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3,
         2, 3, 1, 3, 3, 3, 1, 3, 1, 3, 3, 

In [39]:
inference_model = kr.models.load_model(filepath=inference_model_path)
training_model = kr.models.load_model(filepath=training_model_path)

In [40]:
sample = titanic_data_test.sample(n=1)
input_dict = {name: tf.convert_to_tensor(value) for name, value in sample.items()}
input_dict

{'Pclass': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([3], dtype=int64)>,
 'Sex': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'female'], dtype=object)>,
 'Age': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([27.])>,
 'SibSp': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1], dtype=int64)>,
 'Parch': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0], dtype=int64)>,
 'Fare': <tf.Tensor: shape=(1,), dtype=float64, numpy=array([7.925])>,
 'Embarked': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'S'], dtype=object)>}

In [41]:
prediction = inference_model.predict(input_dict)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step


array([[0.61963636]], dtype=float32)

In [42]:
predictions = inference_model.predict(x=titanic_dataset)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step


array([[0.02990931],
       [0.3144216 ],
       [0.02304282],
       [0.17936237],
       [0.5197228 ],
       [0.12228212],
       [0.31785667],
       [0.05304518],
       [0.6795259 ],
       [0.03222797],
       [0.12220655],
       [0.35094997],
       [0.9620445 ],
       [0.03737288],
       [0.9747287 ],
       [0.8724473 ],
       [0.022188  ],
       [0.2841512 ],
       [0.61963636],
       [0.43821785],
       [0.68195593],
       [0.56051874],
       [0.9909534 ],
       [0.08949408],
       [0.9729398 ],
       [0.05127372],
       [0.9786322 ],
       [0.2841512 ],
       [0.33803028],
       [0.23229979],
       [0.03737288],
       [0.03076835],
       [0.5522429 ],
       [0.4060215 ],
       [0.64331573],
       [0.2841488 ],
       [0.36350477],
       [0.54250395],
       [0.18162231],
       [0.13529949],
       [0.14593613],
       [0.31396914],
       [0.07421533],
       [0.9752322 ],
       [0.97195244],
       [0.1773906 ],
       [0.30003637],
       [0.068

In [43]:
len(predictions)

418